name: make-lint

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hexlet project check
        uses: hexlet/project-action@release
        with:
          hexlet-id: ${{ secrets.HEXLET_ID }}
      - run: make lint
